export const STAFF_SEED = [
    {
      code: 'CSKH100001',
      username: 'lannt',
      name: 'Nguyễn Thị Lan',
      initials: 'TL',
      phone: '0919876543',
      email: 'lan.nt@viago.vn',
      date: '10/04/2026',
      status: 'Đang hoạt động',
      gender: 'Nữ',
      birthDate: '1995-10-12',
      defaultRole: 'Nhân viên CSKH',
      roles: 'NHÂN VIÊN CSKH (5 QUYỀN)',
      permissions: ['khachhang', 'tukhoacam', 'danhgiaphanhoi', 'dothatlac', 'baocao'],
      address: 'Văn phòng VIAGO, TP.HCM',
      notes: 'Hỗ trợ khách hàng xuất sắc',
      logs: []
    },
    {
      code: 'NVBV100125',
      username: 'hoangnv',
      name: 'Nguyễn Việt Hoàng',
      initials: 'VH',
      phone: '0981122334',
      email: 'hoang.nv@gmail.com',
      date: '05/04/2026',
      status: 'Đang hoạt động',
      gender: 'Nam',
      birthDate: '1996-03-22',
      defaultRole: 'Nhân viên bán vé',
      roles: 'NHÂN VIÊN BÁN VÉ (2 QUYỀN)',
      permissions: ['datve', 'baocao'],
      address: 'Văn phòng VIAGO, Hà Nội',
      notes: '',
      logs: []
    },
    {
      code: 'NVDP100003',
      username: 'haiph',
      name: 'Phan Huy Hải',
      initials: 'HH',
      phone: '0979988776',
      email: 'hai.ph@viago.vn',
      date: '12/04/2026',
      status: 'Đang hoạt động',
      gender: 'Nam',
      birthDate: '1993-07-09',
      defaultRole: 'Nhân viên điều phối',
      roles: 'NHÂN VIÊN ĐIỀU PHỐI (3 QUYỀN)',
      permissions: ['dieuphoi', 'baocao', 'nhatky'],
      address: 'Văn phòng VIAGO, Đà Nẵng',
      notes: '',
      logs: []
    },
    {
      code: 'QTV100001',
      username: 'admin_viago',
      name: 'Trần Minh Đức',
      initials: 'MD',
      phone: '0909090909',
      email: 'duc.tm@viago.vn',
      date: '01/01/2026',
      status: 'Đang hoạt động',
      gender: 'Nam',
      birthDate: '1989-12-12',
      defaultRole: 'Quản trị viên',
      roles: 'QUẢN TRỊ VIÊN (13 QUYỀN)',
      permissions: ['datve', 'tintuc', 'dieuphoi', 'khachhang', 'nhanvien', 'chinhsach', 'tukhoacam', 'baocao', 'nhatky', 'danhgiaphanhoi', 'dothatlac', 'thuexehopdong', 'khuyenmai'],
      address: 'VIAGO Headquarter, TP.HCM',
      notes: 'Super admin',
      logs: []
    },
    {
      code: 'CSKH100002',
      username: 'huongvy',
      name: 'Đặng Vy Hương',
      initials: 'VH',
      phone: '0938877665',
      email: 'huong.vd@viago.vn',
      date: '18/04/2026',
      status: 'Đang hoạt động',
      gender: 'Nữ',
      birthDate: '1997-05-15',
      defaultRole: 'Nhân viên CSKH',
      roles: 'NHÂN VIÊN CSKH (5 QUYỀN)',
      permissions: ['khachhang', 'danhgiaphanhoi', 'dothatlac'],
      address: 'Văn phòng VIAGO, Cần Thơ',
      notes: '',
      logs: []
    },
    {
      code: 'NVBV100124',
      username: 'ngocth',
      name: 'Trần Hồng Ngọc',
      initials: 'HN',
      phone: '0945566778',
      email: 'ngoc.th@gmail.com',
      date: '20/04/2026',
      status: 'Đang hoạt động',
      gender: 'Nữ',
      birthDate: '1994-08-30',
      defaultRole: 'Nhân viên bán vé',
      roles: 'NHÂN VIÊN BÁN VÉ (2 QUYỀN)',
      permissions: ['datve', 'baocao'],
      address: 'Văn phòng VIAGO, Hải Phòng',
      notes: '',
      logs: []
    },
    {
      code: 'NVDP100004',
      username: 'quocvn',
      name: 'Vũ Ngọc Quốc',
      initials: 'NQ',
      phone: '0912233445',
      email: 'quoc.vn@viago.vn',
      date: '25/04/2026',
      status: 'Đang hoạt động',
      gender: 'Nam',
      birthDate: '1991-01-20',
      defaultRole: 'Nhân viên điều phối',
      roles: 'NHÂN VIÊN ĐIỀU PHỐI (3 QUYỀN)',
      permissions: ['dieuphoi', 'baocao', 'nhatky'],
      address: 'Văn phòng VIAGO, Nha Trang',
      notes: '',
      logs: []
    },
    {
      code: 'BQL100002',
      username: 'khanhph',
      name: 'Phan Huy Khánh',
      initials: 'HK',
      phone: '0966554433',
      email: 'khanh.ph@viago.vn',
      date: '15/01/2026',
      status: 'Đang hoạt động',
      gender: 'Nam',
      birthDate: '1985-04-18',
      defaultRole: 'Ban quản lý',
      roles: 'BAN QUẢN LÝ (1 QUYỀN)',
      permissions: ['baocao'],
      address: 'Văn phòng VIAGO, TP.HCM',
      notes: '',
      logs: []
    },
    {
      code: 'CSKH100003',
      username: 'yennp',
      name: 'Nguyễn Phương Yến',
      initials: 'PY',
      phone: '0901122334',
      email: 'yen.np@viago.vn',
      date: '02/05/2026',
      status: 'Đã khóa',
      gender: 'Nữ',
      birthDate: '1998-11-02',
      defaultRole: 'Nhân viên CSKH',
      roles: 'NHÂN VIÊN CSKH (5 QUYỀN)',
      permissions: ['khachhang', 'danhgiaphanhoi'],
      address: '15 Lê Duẩn, Quận 1, TP.HCM',
      notes: '',
      logs: [
        { type: 'lock', title: 'Quản lý tài khoản', time: '2026-05-30 09:00:00', desc: 'Khóa tài khoản nhân viên do vi phạm bảo mật thông tin khách hàng.', ip: '127.0.0.1', code: 'VIAGO_LOG_1781200000004_LK2' }
      ],
      lockInfo: {
        date: '2026-05-30 09:00',
        reason: 'Vi phạm bảo mật thông tin khách hàng'
      }
    },
    {
      code: 'NVBV100123',
      username: 'tuanlm',
      name: 'Lê Minh Tuấn',
      initials: 'MT',
      phone: '0937788990',
      email: 'tuan.lm@gmail.com',
      date: '10/05/2026',
      status: 'Đang hoạt động',
      gender: 'Nam',
      birthDate: '1995-02-14',
      defaultRole: 'Nhân viên bán vé',
      roles: 'NHÂN VIÊN BÁN VÉ (2 QUYỀN)',
      permissions: ['datve', 'baocao'],
      address: 'Văn phòng VIAGO, Vũng Tàu',
      notes: '',
      logs: []
    },
    {
      code: 'NVDP100001',
      username: 'NVDP100001',
      name: 'Nguyen Van Dieu Phoi',
      initials: 'DP',
      phone: '0909999999',
      email: 'dieuphoi@viago.vn',
      date: '28/06/2026',
      status: 'Đang hoạt động',
      gender: 'Nam',
      birthDate: '1995-06-28',
      defaultRole: 'Nhân viên điều phối',
      roles: 'NHÂN VIÊN ĐIỀU PHỐI (3 QUYỀN)',
      permissions: ['dieuphoi', 'baocao', 'nhatky'],
      address: 'Văn phòng VIAGO, TP.HCM',
      notes: 'Điều phối chính',
      logs: [
        {
          type: 'update',
          title: 'Quản lý tài khoản',
          time: '2026-06-28 21:15:20',
          desc: 'Thay đổi trạng thái tài khoản nhân viên Hoang Anh Tuan (Mã: BQL100001) sang Đã khóa',
          ip: '127.0.0.1',
          code: 'TXP_LOG_1782656120907_KYKM9R'
        },
        {
          type: 'update',
          title: 'Quản lý tài khoản',
          time: '2026-06-25 10:14:00',
          desc: 'Cập nhật thông tin cơ bản cho nhân viên NV002',
          ip: '127.0.0.1',
          code: 'TXP_LOG_1782656109459_ACV24M'
        },
        {
          type: 'update',
          title: 'Quản lý tài khoản',
          time: '2026-06-22 09:30:15',
          desc: 'Đồng bộ quyền hạn cho nhân viên mới',
          ip: '127.0.0.1',
          code: 'TXP_LOG_1782656097969_NR2888'
        },
        {
          type: 'update',
          title: 'Quản lý tài khoản',
          time: '2026-06-18 14:22:00',
          desc: 'Thay đổi chức vụ của nhân viên NV005',
          ip: '127.0.0.1',
          code: 'TXP_LOG_1782656097875_E5YBDC'
        },
        {
          type: 'update',
          title: 'Quản lý tài khoản',
          time: '2026-06-10 16:45:10',
          desc: 'Cập nhật thông tin liên hệ nhân viên NV007',
          ip: '127.0.0.1',
          code: 'TXP_LOG_1782656097872_06J9IR'
        },
        {
          type: 'update',
          title: 'Quản lý tài khoản',
          time: '2026-05-15 08:30:00',
          desc: 'Xem danh sách tài khoản nhân viên',
          ip: '127.0.0.1',
          code: 'TXP_LOG_1782656097872_0QUG7N'
        }
      ]
    },
    {
      code: 'BQL100001',
      username: 'quanly1',
      name: 'Hoang Anh Tuan',
      initials: 'AT',
      phone: '0901234567',
      email: 'tuan.ha@gmail.com',
      date: '10/01/2026',
      status: 'Đang hoạt động',
      gender: 'Nam',
      birthDate: '1988-04-12',
      defaultRole: 'Ban quản lý',
      roles: 'BAN QUẢN LÝ (1 QUYỀN)',
      permissions: ['baocao'],
      address: '12 Nguyễn Trãi, Quận 5, TP.HCM',
      notes: 'Làm việc xuất sắc, trách nhiệm cao.',
      logs: [
        { type: 'create', title: 'Khởi tạo tài khoản', time: '2026-01-10 08:00:00', desc: 'Khởi tạo tài khoản quản lý hệ thống.', ip: '127.0.0.1', code: 'VIAGO_LOG_1781200000000_QA1' },
        { type: 'update', title: 'Báo cáo', time: '2026-05-20 11:30:00', desc: 'Xem báo cáo doanh thu tháng 4/2026', ip: '127.0.0.1', code: 'VIAGO_LOG_1781200000000_QA2' },
        { type: 'update', title: 'Báo cáo & Xuất file', time: '2026-06-05 14:15:00', desc: 'Xuất dữ liệu danh sách khách hàng tháng 5', ip: '127.0.0.1', code: 'VIAGO_LOG_1781200000000_QA3' }
      ]
    },
    {
      code: 'CL100301',
      username: 'tuanha',
      name: 'Hoàng Anh Tuấn',
      initials: 'AT',
      phone: '0908765432',
      email: 'tuanha.cl@gmail.com',
      date: '15/02/2026',
      status: 'Đang hoạt động',
      gender: 'Nam',
      birthDate: '1990-11-23',
      defaultRole: 'Ban quản lý',
      roles: 'BAN QUẢN LÝ (1 QUYỀN)',
      permissions: ['baocao'],
      address: '45 Lê Lợi, Quận 1, TP.HCM',
      notes: '',
      logs: [
        { type: 'create', title: 'Cấp quyền truy cập', time: '2026-02-15 09:30:00', desc: 'Thêm mới tài khoản Ban quản lý.', ip: '127.0.0.1', code: 'VIAGO_LOG_1781200000001_TH1' },
        { type: 'update', title: 'Báo cáo', time: '2026-04-12 10:00:00', desc: 'Xem báo cáo hoạt động vận hành quý 1', ip: '127.0.0.1', code: 'VIAGO_LOG_1781200000001_TH2' },
        { type: 'update', title: 'Báo cáo & Xuất file', time: '2026-06-12 15:30:00', desc: 'Xuất file báo cáo tài chính tuần', ip: '127.0.0.1', code: 'VIAGO_LOG_1781200000001_TH3' }
      ]
    },
    {
      code: 'CL100303',
      username: 'trangpt',
      name: 'Trần Thị Trang',
      initials: 'TT',
      phone: '0912345678',
      email: 'trangpt@gmail.com',
      date: '20/02/2026',
      status: 'Đang hoạt động',
      gender: 'Nữ',
      birthDate: '1993-08-15',
      defaultRole: 'Nhân viên bán vé',
      roles: 'NHÂN VIÊN BÁN VÉ (2 QUYỀN)',
      permissions: ['datve', 'baocao'],
      address: '78 CMT8, Quận 3, TP.HCM',
      notes: '',
      logs: [
        { type: 'create', title: 'Đăng nhập lần đầu', time: '2026-02-20 10:15:00', desc: 'Nhân viên đăng nhập thành công vào hệ thống bán vé.', ip: '192.168.1.55', code: 'VIAGO_LOG_1781200000002_TR1' },
        { type: 'update', title: 'Đăng nhập', time: '2026-05-10 09:12:00', desc: 'Nhân viên đăng nhập thành công vào hệ thống Admin.', ip: '192.168.1.55', code: 'VIAGO_LOG_1781200000002_TR2' },
        { type: 'update', title: 'Đăng nhập', time: '2026-06-20 08:45:00', desc: 'Nhân viên đăng nhập thành công vào hệ thống Admin.', ip: '192.168.1.55', code: 'VIAGO_LOG_1781200000002_TR3' }
      ]
    },
    {
      code: 'NVDP100002',
      username: 'linhnv',
      name: 'Nguyễn Văn Linh',
      initials: 'VL',
      phone: '0934567890',
      email: 'linhnv.dispatch@gmail.com',
      date: '01/03/2026',
      status: 'Đang hoạt động',
      gender: 'Nam',
      birthDate: '1992-05-18',
      defaultRole: 'Nhân viên điều phối',
      roles: 'NHÂN VIÊN ĐIỀU PHỐI (3 QUYỀN)',
      permissions: ['dieuphoi', 'baocao', 'nhatky'],
      address: '109 Lý Thường Kiệt, Quận Tân Bình, TP.HCM',
      notes: '',
      logs: [
        {
          type: 'update',
          title: 'Quản lý lịch trình',
          time: '2026-06-28 20:05:00',
          desc: 'Cập nhật chuyến xe Sài Gòn - Vũng Tàu lúc 08:00',
          ip: '192.168.1.60',
          code: 'VIAGO_LOG_1782656081234_UPD332'
        },
        {
          type: 'update',
          title: 'Quản lý lịch trình',
          time: '2026-06-15 14:20:00',
          desc: 'Cập nhật lịch trình tuyến xe limousine Vũng Tàu',
          ip: '192.168.1.60',
          code: 'VIAGO_LOG_1782656081234_UPD333'
        },
        {
          type: 'update',
          title: 'Quản lý lịch trình',
          time: '2026-05-25 11:00:00',
          desc: 'Điều chỉnh tài xế cho chuyến xe VTA-002',
          ip: '192.168.1.60',
          code: 'VIAGO_LOG_1782656081234_UPD334'
        }
      ]
    },
    {
      code: 'NVDP100069',
      username: 'dungpt',
      name: 'Phạm Thanh Dũng',
      initials: 'TD',
      phone: '0907475177',
      email: 'dungpt.dispatch@gmail.com',
      date: '12/03/2026',
      status: 'Đã khóa',
      gender: 'Nam',
      birthDate: '1991-02-25',
      defaultRole: 'Nhân viên điều phối',
      roles: 'NHÂN VIÊN ĐIỀU PHỐI (3 QUYỀN)',
      permissions: ['dieuphoi', 'baocao', 'nhatky'],
      address: '12 Trần Phú, Quận 5, TP.HCM',
      notes: '',
      logs: [
        {
          type: 'lock',
          title: 'Quản lý tài khoản',
          time: '2026-05-20 14:00:00',
          desc: 'Khóa tài khoản nhân viên. Lý do: Nghỉ việc tạm thời',
          ip: '127.0.0.1',
          code: 'VIAGO_LOG_1781200000003_LK1'
        },
        {
          type: 'update',
          title: 'Quản lý lịch trình',
          time: '2026-04-05 08:30:00',
          desc: 'Đồng bộ danh sách tuyến xe liên tỉnh',
          ip: '127.0.0.1',
          code: 'VIAGO_LOG_1781200000003_UPD2'
        }
      ],
      lockInfo: {
        date: '2026-05-20 14:00',
        reason: 'Nghỉ việc tạm thời'
      }
    },
    {
      code: 'NVBV100127',
      username: 'maitt',
      name: 'Trần Thị Mai',
      initials: 'TM',
      phone: '0934567890',
      email: 'mai.tt@yahoo.com',
      date: '20/03/2026',
      status: 'Đang hoạt động',
      gender: 'Nữ',
      birthDate: '1993-09-08',
      defaultRole: 'Nhân viên bán vé',
      roles: 'NHÂN VIÊN BÁN VÉ (2 QUYỀN)',
      permissions: ['datve', 'baocao'],
      address: '90 Trần Hưng Đạo, Quận 1, TP.HCM',
      notes: '',
      logs: [
        {
          type: 'update',
          title: 'Đặt vé',
          time: '2026-06-28 21:02:15',
          desc: 'Đặt vé thành công cho khách hàng Nguyen Van A, Mã vé: VIAGO_TKT_12345',
          ip: '192.168.1.102',
          code: 'VIAGO_LOG_1782656102123_TKT1'
        },
        {
          type: 'update',
          title: 'Tra cứu vé',
          time: '2026-06-24 16:30:00',
          desc: 'Tra cứu thông tin vé của khách hàng Tran Thi C',
          ip: '192.168.1.102',
          code: 'VIAGO_LOG_1782656102123_TKT2'
        },
        {
          type: 'update',
          title: 'Hủy vé',
          time: '2026-06-18 10:15:00',
          desc: 'Hủy vé đặt thành công cho mã vé VIAGO_TKT_00129',
          ip: '192.168.1.102',
          code: 'VIAGO_LOG_1782656102123_TKT3'
        }
      ]
    },
    {
      code: 'NVBV100126',
      username: 'kiemnt',
      name: 'Nguyễn Thị Kiểm',
      initials: 'TK',
      phone: '0908739484',
      email: 'kiem.nt@gmail.com',
      date: '22/03/2026',
      status: 'Đang hoạt động',
      gender: 'Nữ',
      birthDate: '1980-05-31',
      defaultRole: 'Nhân viên bán vé',
      roles: 'NHÂN VIÊN BÁN VÉ (2 QUYỀN)',
      permissions: ['datve', 'baocao'],
      address: '34 Nguyễn Văn Cừ, Quận 5, TP.HCM',
      notes: '',
      logs: [
        {
          type: 'update',
          title: 'Đặt vé',
          time: '2026-06-28 20:45:00',
          desc: 'Đặt vé thành công cho khách hàng Tran Thi B, Mã vé: VIAGO_TKT_12346',
          ip: '192.168.1.103',
          code: 'VIAGO_LOG_1782656085123_TKT2'
        },
        {
          type: 'update',
          title: 'Chỉnh sửa thông tin vé',
          time: '2026-06-26 11:20:00',
          desc: 'Thay đổi thông tin ghế ngồi cho vé VIAGO_TKT_12346 từ A1 sang A2',
          ip: '192.168.1.103',
          code: 'VIAGO_LOG_1782656085123_TKT3'
        },
        {
          type: 'update',
          title: 'Đổi mật khẩu',
          time: '2026-06-14 15:40:00',
          desc: 'Yêu cầu thay đổi mật khẩu hệ thống thành công',
          ip: '192.168.1.103',
          code: 'VIAGO_LOG_1782656085123_TKT4'
        }
      ]
    }
  ];
export const PERMISSION_MODULES = [
    { key: 'datve', title: 'Quản lý vé', desc: 'Cho phép truy cập và thực hiện các nghiệp vụ đặt vé mới, tra cứu bối cảnh vé, hoàn tiền và sửa thông tin vé.', expanded: false, icon: 'ticket' },
    { key: 'tintuc', title: 'Quản lý tin tức', desc: 'Cho phép tạo, sửa, xóa các bài viết tin tức trên trang chủ.', expanded: false, icon: 'news' },
    { key: 'dieuphoi', title: 'Quản lý điều hành', desc: 'Cho phép điều hành tuyến xe, lịch trình, xe chạy và tài xế.', expanded: false, icon: 'dispatch' },
    { key: 'khachhang', title: 'Quản lý khách hàng', desc: 'Cho phép quản lý tài khoản khách hàng, xem đánh giá phản hồi.', expanded: false, icon: 'customer' },
    { key: 'nhanvien', title: 'Quản lý nhân viên', desc: 'Cho phép quản lý tài khoản nhân viên, cấu hình quyền hạn.', expanded: false, icon: 'employee' },
    { key: 'chinhsach', title: 'Quản lý chính sách', desc: 'Cho phép điều chỉnh chính sách, điều khoản dịch vụ.', expanded: false, icon: 'policy' },
    { key: 'tukhoacam', title: 'Quản lý từ khóa cấm', desc: 'Cho phép cấu hình các từ khóa cấm trong đánh giá.', expanded: false, icon: 'ban' },
    { key: 'baocao', title: 'Báo cáo', desc: 'Cho phép xem báo cáo doanh thu, sản lượng, vận hành.', expanded: false, icon: 'report' },
    { key: 'nhatky', title: 'Quản lý nhật ký', desc: 'Cho phép xem nhật ký hoạt động hệ thống.', expanded: false, icon: 'log' },
    { key: 'danhgiaphanhoi', title: 'Quản lý đánh giá và phản hồi', desc: 'Cho phép quản lý, phản hồi các đánh giá của khách hàng.', expanded: false, icon: 'feedback' },
    { key: 'dothatlac', title: 'Quản lý đồ thất lạc', desc: 'Cho phép tìm kiếm, cập nhật thông tin đồ đạc thất lạc.', expanded: false, icon: 'lost_found' },
    { key: 'thuexehopdong', title: 'Quản lý yêu cầu thuê xe hợp đồng', desc: 'Cho phép xử lý các yêu cầu thuê xe du lịch, hợp đồng.', expanded: false, icon: 'charter' },
    { key: 'khuyenmai', title: 'Quản lý khuyến mãi', desc: 'Cho phép quản lý các chương trình ưu đãi, mã giảm giá.', expanded: false, icon: 'promo' },
  ];
